DELETE FROM GESTION_TICKETS_TEST_INTEGRATION.D_DROITCRUD_SIROLE
WHERE IdSIRole = 1;
DELETE FROM GESTION_TICKETS_TEST_INTEGRATION.D_DROITCRUD_SIROLE
WHERE IdSIRole = 2;

DELETE FROM GESTION_TICKETS_TEST_INTEGRATION.D_MATERIEL_CATEGORIE
WHERE IdCategorie = 1;
DELETE FROM GESTION_TICKETS_TEST_INTEGRATION.D_MATERIEL_CATEGORIE
WHERE IdCategorie = 2;
DELETE FROM GESTION_TICKETS_TEST_INTEGRATION.D_MATERIEL_CATEGORIE
WHERE IdCategorie = 9;
DELETE FROM GESTION_TICKETS_TEST_INTEGRATION.D_MATERIEL_CATEGORIE
WHERE IdCategorie = 10;

DELETE FROM GESTION_TICKETS_TEST_INTEGRATION.D_CATEGORIE
WHERE Id = 1;
DELETE FROM GESTION_TICKETS_TEST_INTEGRATION.D_CATEGORIE
WHERE Id = 2;
DELETE FROM GESTION_TICKETS_TEST_INTEGRATION.D_CATEGORIE
WHERE Id = 8;
DELETE FROM GESTION_TICKETS_TEST_INTEGRATION.D_CATEGORIE
WHERE Id = 9;
DELETE FROM GESTION_TICKETS_TEST_INTEGRATION.D_CATEGORIE
WHERE Id = 10;

DELETE FROM GESTION_TICKETS_TEST_INTEGRATION.D_MATERIEL_DETRUIT
WHERE Id = 8;
DELETE FROM GESTION_TICKETS_TEST_INTEGRATION.D_MATERIEL_DETRUIT
WHERE Id = 11;

DELETE FROM GESTION_TICKETS_TEST_INTEGRATION.D_MATERIEL
WHERE Id = 1;
DELETE FROM GESTION_TICKETS_TEST_INTEGRATION.D_MATERIEL
WHERE Id = 2;
DELETE FROM GESTION_TICKETS_TEST_INTEGRATION.D_MATERIEL
WHERE Id = 3;
DELETE FROM GESTION_TICKETS_TEST_INTEGRATION.D_MATERIEL
WHERE Id = 4;
DELETE FROM GESTION_TICKETS_TEST_INTEGRATION.D_MATERIEL
WHERE Id = 29;

DELETE FROM GESTION_TICKETS_TEST_INTEGRATION.D_MCONTRAT
WHERE Id = 1;
DELETE FROM GESTION_TICKETS_TEST_INTEGRATION.D_MCONTRAT
WHERE Id = 2;
DELETE FROM GESTION_TICKETS_TEST_INTEGRATION.D_MCONTRAT
WHERE Id = 3;
DELETE FROM GESTION_TICKETS_TEST_INTEGRATION.D_MCONTRAT
WHERE Id = 4;
DELETE FROM GESTION_TICKETS_TEST_INTEGRATION.D_MCONTRAT
WHERE Id = 5;
DELETE FROM GESTION_TICKETS_TEST_INTEGRATION.D_MCONTRAT
WHERE Id = 6;

DELETE FROM GESTION_TICKETS_TEST_INTEGRATION.D_ENTREPRISE
WHERE Id = 1;
DELETE FROM GESTION_TICKETS_TEST_INTEGRATION.D_ENTREPRISE
WHERE Id = 2;
DELETE FROM GESTION_TICKETS_TEST_INTEGRATION.D_ENTREPRISE
WHERE Id = 3;
DELETE FROM GESTION_TICKETS_TEST_INTEGRATION.D_ENTREPRISE
WHERE Id = 4;
DELETE FROM GESTION_TICKETS_TEST_INTEGRATION.D_ENTREPRISE
WHERE Id = 5;

DELETE FROM GESTION_TICKETS_TEST_INTEGRATION.users
WHERE id = 82001;
DELETE FROM GESTION_TICKETS_TEST_INTEGRATION.users
WHERE id = 96101;
DELETE FROM GESTION_TICKETS_TEST_INTEGRATION.users
WHERE id = 96129;
DELETE FROM GESTION_TICKETS_TEST_INTEGRATION.users
WHERE id = 96106;

DELETE FROM GESTION_TICKETS_TEST_INTEGRATION.users
WHERE id = 96128;
DELETE FROM GESTION_TICKETS_TEST_INTEGRATION.users
WHERE id = 96111;
DELETE FROM GESTION_TICKETS_TEST_INTEGRATION.users
WHERE id = 96102;



DELETE FROM GESTION_TICKETS_TEST_INTEGRATION.D_SIROLE
WHERE Id = 1;
DELETE FROM GESTION_TICKETS_TEST_INTEGRATION.D_SIROLE
WHERE Id = 2;
DELETE FROM GESTION_TICKETS_TEST_INTEGRATION.D_SIROLE
WHERE Id = 3;

DELETE FROM GESTION_TICKETS_TEST_INTEGRATION.D_DROITCRUD
WHERE Id = 1;
DELETE FROM GESTION_TICKETS_TEST_INTEGRATION.D_DROITCRUD
WHERE Id = 2;
DELETE FROM GESTION_TICKETS_TEST_INTEGRATION.D_DROITCRUD
WHERE Id = 3;
DELETE FROM GESTION_TICKETS_TEST_INTEGRATION.D_DROITCRUD
WHERE Id = 4;
DELETE FROM GESTION_TICKETS_TEST_INTEGRATION.D_DROITCRUD
WHERE Id = 5;
















